spring:
  application:
    name: ms-ne-gestionIntencion

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=sqldb1
    username: sa
    password: sa
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    database-platform: org.hibernate.dialect.SQLServerDialect

config:
  stopBubbling: true

lombok:
  addLombokGeneratedAnnotation: true
